import { Global } from '@emotion/react'

const Fonts = () => (
  <Global
    styles={`
    @font-face{font-family:'Gilroy';src:url('https://marketplace.graphlinq.io/fonts/gilroy/Gilroy-Regular.eot');src:local('Gilroy Regular'),local('Gilroy-Regular'),url('./fonts/gilroy/Gilroy-Regular.eot?#iefix') format('embedded-opentype'),url('./fonts/gilroy/Gilroy-Regular.woff2') format('woff2'),url('./fonts/gilroy/Gilroy-Regular.woff') format('woff'),url('./fonts/gilroy/Gilroy-Regular.ttf') format('truetype');font-weight:normal;font-style:normal;}
    @font-face{font-family:'Gilroy';src:url('https://marketplace.graphlinq.io/fonts/gilroy/Gilroy-Bold.eot');src:local('Gilroy Bold'),local('Gilroy-Bold'),url('./fonts/gilroy/Gilroy-Bold.eot?#iefix') format('embedded-opentype'),url('./fonts/gilroy/Gilroy-Bold.woff2') format('woff2'),url('./fonts/gilroy/Gilroy-Bold.woff') format('woff'),url('./fonts/gilroy/Gilroy-Bold.ttf') format('truetype');font-weight:bold;font-style:normal;}
    @font-face{font-family:'Gilroy';src:url('https://marketplace.graphlinq.io/fonts/gilroy/Gilroy-Black.eot');src:local('Gilroy Black'),local('Gilroy-Black'),url('./fonts/gilroy/Gilroy-Black.eot?#iefix') format('embedded-opentype'),url('./fonts/gilroy/Gilroy-Black.woff2') format('woff2'),url('./fonts/gilroy/Gilroy-Black.woff') format('woff'),url('./fonts/gilroy/Gilroy-Black.ttf') format('truetype');font-weight:900;font-style:normal;}
    @font-face{font-family:'Gilroy';src:url('https://marketplace.graphlinq.io/fonts/gilroy/Gilroy-Light.eot');src:local('Gilroy Light'),local('Gilroy-Light'),url('./fonts/gilroy/Gilroy-Light.eot?#iefix') format('embedded-opentype'),url('./fonts/gilroy/Gilroy-Light.woff2') format('woff2'),url('./fonts/gilroy/Gilroy-Light.woff') format('woff'),url('./fonts/gilroy/Gilroy-Light.ttf') format('truetype');font-weight:300;font-style:normal;}
    @font-face{font-family:'Gilroy';src:url('https://marketplace.graphlinq.io/fonts/gilroy/Gilroy-Medium.eot');src:local('Gilroy Medium'),local('Gilroy-Medium'),url('./fonts/gilroy/Gilroy-Medium.eot?#iefix') format('embedded-opentype'),url('./fonts/gilroy/Gilroy-Medium.woff2') format('woff2'),url('./fonts/gilroy/Gilroy-Medium.woff') format('woff'),url('./fonts/gilroy/Gilroy-Medium.ttf') format('truetype');font-weight:500;font-style:normal;}
    @font-face{font-family:'Gilroy';src:url('https://marketplace.graphlinq.io/fonts/gilroy/Gilroy-MediumItalic.eot');src:local('Gilroy Medium Italic'),local('Gilroy-MediumItalic'),url('./fonts/gilroy/Gilroy-MediumItalic.eot?#iefix') format('embedded-opentype'),url('./fonts/gilroy/Gilroy-MediumItalic.woff2') format('woff2'),url('./fonts/gilroy/Gilroy-MediumItalic.woff') format('woff'),url('./fonts/gilroy/Gilroy-MediumItalic.ttf') format('truetype');font-weight:500;font-style:italic;}
    @font-face{font-family:'Gilroy';src:url('https://marketplace.graphlinq.io/fonts/gilroy/Gilroy-UltraLight.eot');src:local('Gilroy UltraLight'),local('Gilroy-UltraLight'),url('./fonts/gilroy/Gilroy-UltraLight.eot?#iefix') format('embedded-opentype'),url('./fonts/gilroy/Gilroy-UltraLight.woff2') format('woff2'),url('./fonts/gilroy/Gilroy-UltraLight.woff') format('woff'),url('./fonts/gilroy/Gilroy-UltraLight.ttf') format('truetype');font-weight:200;font-style:normal;}
    @font-face{font-family:'Gilroy';src:url('https://marketplace.graphlinq.io/fonts/gilroy/Gilroy-RegularItalic.eot');src:local('Gilroy Regular Italic'),local('Gilroy-RegularItalic'),url('./fonts/gilroy/Gilroy-RegularItalic.eot?#iefix') format('embedded-opentype'),url('./fonts/gilroy/Gilroy-RegularItalic.woff2') format('woff2'),url('./fonts/gilroy/Gilroy-RegularItalic.woff') format('woff'),url('./fonts/gilroy/Gilroy-RegularItalic.ttf') format('truetype');font-weight:normal;font-style:italic;}
    @font-face{font-family:'Gilroy';src:url('https://marketplace.graphlinq.io/fonts/gilroy/Gilroy-Extrabold.eot');src:local('Gilroy Extrabold'),local('Gilroy-Extrabold'),url('./fonts/gilroy/Gilroy-Extrabold.eot?#iefix') format('embedded-opentype'),url('./fonts/gilroy/Gilroy-Extrabold.woff2') format('woff2'),url('./fonts/gilroy/Gilroy-Extrabold.woff') format('woff'),url('./fonts/gilroy/Gilroy-Extrabold.ttf') format('truetype');font-weight:800;font-style:normal;}
    @font-face{font-family:'Gilroy';src:url('https://marketplace.graphlinq.io/fonts/gilroy/Gilroy-LightItalic.eot');src:local('Gilroy Light Italic'),local('Gilroy-LightItalic'),url('./fonts/gilroy/Gilroy-LightItalic.eot?#iefix') format('embedded-opentype'),url('./fonts/gilroy/Gilroy-LightItalic.woff2') format('woff2'),url('./fonts/gilroy/Gilroy-LightItalic.woff') format('woff'),url('./fonts/gilroy/Gilroy-LightItalic.ttf') format('truetype');font-weight:300;font-style:italic;}
      `}
  />
)

export default Fonts
